export const ADD_TO_CART='ADD_TO_CART';
export const BUY_NOW='BUY_NOW';
export const  REMOVE_FROM_CART='REMOVE_FROM_CART';
export const CART_INIT='CART_INIT';

export const LOADING ='LOADING';
export const ITEM_SELECTOR='ITEM_SELECTOR';
export const DETAILS_CLOSED='DETAILS_CLOSED';

export const CHECKOUT_START='CHECKOUT_START';
export const CHECKOUT_SUCCED='CHECKOUT_SUCCED';
export const CHECKOUT_FAILED='CHECKOUT_FAILED';

export const ORDERS_COUNT='ORDERS_COUNT';
export const ORDERS_COUNT_INIT='ORDERS_COUNT_INIT';

export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';
export const AUTH_REDIRECT_LINK='AUTH_REDIRECT_LINK';

export const FETCH_PRODUCTS_START= 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESSS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL= 'FETCH_PRODUCTS_FAIL';

export const ADD_PRODUCTS_START= 'ADD_PRODUCTS_START';
export const ADD_PRODUCTS_SUCCESS= 'ADD_PRODUCTS_SUCCESS';
export const ADD_PRODUCTS_FAILED= 'ADD_PRODUCTS_FAILED';
export const ADD_PRODUCTS_MODAL_HANDLER= 'ADD_PRODUCTS_MODAL_HANDLER';